services:
  mysql:
    image: mysql:latest
    container_name: mysql-loiane-class
    environment:
      - 'MYSQL_DATABASE=mydb'
      - 'MYSQL_PASSWORD=123456'
      - 'MYSQL_ROOT_PASSWORD=123456'
      - 'MYSQL_USER=myuser'
    ports:
      - "3306:3306"
    mem_limit: 512m
